### PR TITLE
Added WP_User->$data

### PR DESCRIPTION
**Pull request by marekdedic**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@marekdedic Have you considered contributing upstream to WordPress core?

**Comment by marekdedic** [comment]
Haha, I have... see #1

The main issue is that the WordPress guidelines are geared towards readability by users, not linters - meaning they have a rule to only document things once - which is very reasonable from a developer perspective, but totally useless if you want to use a linter on the annotations as multiple functions share the same parameters but they are only documented in one of them :/

**Comment by szepeviktor** [comment]
> multiple functions share the same parameters but they are only documented in one of them :/

Oh nooooooooo! This is terrible.
Could you show me 1 example in https://github.com/WordPress/WordPress/tree/6.0 ?

**Comment by marekdedic** [comment]
For example: Basically every `add_*` function in `WP_Customize_Manager` does this - see https://developer.wordpress.org/reference/classes/wp_customize_manager/add_control/ and compare it to https://developer.wordpress.org/reference/classes/wp_customize_control/__construct/

This is one of the main reasons why I decided to just do the hard work myself, instead of using some code that extracts it from WP source (like yours :) ) - you can only go so far if your input data is low quality.

**Comment by szepeviktor** [comment]
Ah! So you refer to missing array shapes.

**Comment by marekdedic** [comment]
Yeah, support for array shapes is abysmal in WordPress :D

**Pull request merged**
