### PR TITLE
Define constants from $_GET superglobal

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
These booleans could be simple true or false.
PHPStan has [`dynamicConstantNames:`](https://github.com/szepeviktor/phpstan-wordpress/blob/e487dc725845ac914681e148d0e8ac479ad887ec/extension.neon#L93-L97).
I refrain from talking other static analysis tools 😉

**Comment by szepeviktor** [comment]
I know - I know, this is an esoteric package 🔮

**Comment by szepeviktor** [comment]
💡 The .neon file has tabs and spaces also.

**Comment by marekdedic** [comment]
Hi,
thanks for noticing mixed tabs and spaces - #66. I am a bit confused whether this could remove the need for `dynamicConstantNames` for users of the stubs?

**Comment by szepeviktor** [comment]
> whether this could remove the need for `dynamicConstantNames` for users of the stubs?

When using `dynamicConstantNames` the constants have to be still defined.

**Comment by marekdedic** [comment]
Yeah, but in the current way of defining it, every user of `wordpress-stubs` has to add `dynamicConstantNames` to their `phpstan.neon` - if you knew of a way of removing this requirement, that would be great...

**Pull request closed without merging**
