### PR TITLE
Convert Docblocks to typehints

### PR DESCRIPTION
**Pull request by szepeviktor**
@marekdedic Would this work for you **in theory**?

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://github.com/skaut/wordpress-stubs/blob/73b49c01b956eb0c5a295d31e95f20fb7db3807f/composer.json#L29-L31

Or do you run tools on lower than PHP 7.4 version?

**Comment by marekdedic** [comment]
Hi,

I have plugins that still support PHP 5.6, however, I am not running any linting on 5.6, so that probably wouldn't be an issue...

What's the benefit of this change though? With the current setup, 5.6 still works, I don't think it's worth breaking that if there'd be no upside...

**Comment by szepeviktor** [comment]
> What's the benefit of this change though?

PHPDoc brought then future features to PHP.
Now many of those landed in PHP.

So no reason to use legacy technology.
_Old Ways Die Slow_ ....

**Comment by marekdedic** [comment]
Yeah, I personally don't think that's reason enough to switch... I'm not strictly against the change, but if it breaks 5.6 support while offering nothing in return. I don't think that's a good use of time :)

**Comment by szepeviktor** [comment]
For me planting a seed in your mind is enough :)

**Pull request closed without merging**
